### ISSUE TITLE
get transactions from Ethereum Address and provide JSON data as API

### ISSUE THREAD

**Issue by geleeroyale** [geleeroyale/donation-leaderboard#10]

**Comment by wildmolasses** [comment]
Hi @geleeroyale, could you explain this issue further please? It looks like we are already doing this via etherscan. If we wish to switch away from etherscan, I believe each leaderboard would need to have access to a full node that it can pull tx data from. To my knowledge, this problem is not solved with web3 alone.

**Comment by sponnet** [comment]
you need to iterate all blocks to get a full TX history of a given account, something that etherscan does for you when you use their API.

**Comment by geleeroyale** [comment]
Yes. We do want to run a node that can be used for many purposes - one of them to do address scraping. @mex20 - @emex on Riot.im is on this. Should be done syncing by now but I think he is traveling at the moment.

The problems with using Etherscan API are:
- Dependency on third party (etherscan) to be up and not change their API request scheme
- Even worse etherscan only allows 5 requests per hour

**Comment by sponnet** [comment]
I once wrote something that indexes balances ( for ERC-20 tokens ) and exposes the results via an API. Maybe that could be easily refurbished to do the above. 
https://github.com/sponnet/balancecruncher

**Comment by geleeroyale** [comment]
As far as I can tell with my limited knowledge that looks pretty good indeed.

Additionally, I think it would be awesome to start this here with listing transactions and let it become an opensource API for querying the blockchain. The ERC20 functionality could be useful here.

**Comment by maxkant** [comment]
I made a simple example leaderboard using web3 when I first heard about this project in the contributors channel.

I was offline since I've been working on it and things seem to have progressed more here than on my end, but I thought I'd share it. Maybe it'll be useful: https://github.com/maxskant/eth-leaderboard-web3

Right now it can grab all the transactions from a local testrpc instance and find all of them going to a certain account. I also set up a little deploy script to have the accounts send random transactions amongst themselves.

**Comment by geleeroyale** [comment]
Interesting. We now have three proposed solutions. I have to say I don't know enough about the differences to decide which solution to go for.

I would actually go for the fastest implementation atm, because time is an issue. In another round we can go for the more robust version. 

@maxskant Can you try integrating your code into this repo? ... in any case, it was not for nothing and you will get rewarded even if we decide to go with other code. thanks again all of you for your great contributions!

**Comment by mex20** [comment]
I am back online from travel! I am currently reading through the other two proposed projects. I think that it makes sense to go with one of those two since they have a lot of work done already, so that we can be ready for scalingNOW! in a couple of weeks. I think the thing that I was working on wont be ready by the time it is needed at scalingNOW! 

As far as which one will work best for this project, I will update when I am done reviewing. These are pretty awesome prjoects @maxskant and @sponnet !

**Comment by geleeroyale** [comment]
Yeah @mex20 don't worry for this time. We are close to deploy and can substitue stuff for the next implementation. Making an open API is still in the room.

**Comment by sponnet** [comment]
I'll integrate the web3 listener for this iteration
