### ISSUE TITLE
Validate input fields

### ISSUE THREAD

**Issue by geleeroyale** [geleeroyale/donation-leaderboard#21]

**Comment by wildmolasses** [comment]
Hi, double checking this issue; what would we like to validate? I remember we discussed validating the 'from' address to make sure it was a valid ethereum address. But since there's no 'from' input field on our app, do we get a chance to validate it? Either way, will be happy to work on it. Other possible fields to validate:

- remarks (should it be under a certain length? can research)
- donation amount (should we check for zero?)

**Comment by geleeroyale** [comment]
The form that should be validated is the transaction form on line #137 (validate ETH adddress). Zero should indeed not be possible because we filter the list out - even if somebody signed a message they need to put at least 1 wei there

**Comment by sponnet** [comment]
isAddress function : https://github.com/ethereumjs/ethereumjs-util/blob/master/docs/index.md#isvalidaddress

**Comment by geleeroyale** [comment]
Don't think any validators are necessary anymore - ethAddress filters with auto-update and sending a zero value transaction to change remark should stay possible
